[package]
name = "tui"
version = "0.1.0"
authors = ["Florian Dehau <florian.dehau@telecomnancy.net>"]

[dependencies]
termion = "1.1.1"
bitflags = "0.7"
cassowary = "0.2.0"
log = "0.3"
unicode-segmentation = "0.1.2"
unicode-width = "0.1.3"

[dev-dependencies]
log4rs = "*"
rand = "0.3"
